on:
  push:
    tags:
      - 'v*'

name: Create release

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        cache: npm
    - name: Install latest npm version
      run: npm install -g npm@latest
    - name: Install dependencies and build
      run: npm ci
    - name: Publish package
      run: npm publish --provenance
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
